camera_id: front
openscan_camera_node_listen_port: 8080
openscan_camera_node_profile_overrides:
  video_1080p25_locked:
    camera_controls:
      awbgains: [1.75, 1.42]
      lens_position: 1.8
  video_1080p50_experimental_locked:
    camera_controls:
      awbgains: [1.75, 1.42]
      lens_position: 1.8
  timelapse_1080p6_locked:
    camera_controls:
      awbgains: [1.75, 1.42]
      lens_position: 1.8
